version: '3.3'
services:
  redis:
    image: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: kartoza/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgsql_master
      POSTGRES_PASSWORD: blockcorp1234#
      POSTGRES_DB: blockcorp
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - pg-data:/var/lib/postgresql
volumes:
  redis-data:
  pg-data: